Collapse linked sources if more than 5 entries are included
OWASP/OpenCRE pull request #458
Opened 2024-01-02 21:04 UTC by restylianos

### Changes
- Collapse **linked sources** if they contain more than 5 entries
- Fix missing div keys after the use of Array.prototype.map
- Lint fixes (make lint introduced several changes in python files)
- Isolate link components and SimpleView
- Remove unused vars and console logs

2024-01-05 15:02 UTC, restylianos commented
> Hey @restylianos , thanks a lot for the PR! Can you please fix the linting?

Hi, @northdpole it should be ok now. Please note that 
**[local setup]**
`black --version
black, 24.1a1 
Python (CPython) 3.10.12` 
**[super-linter@v4]**
`black==22.12.0`

2024-01-06 19:28 UTC, northdpole requested changes
@restylianos , thanks a ton for the work on this, you have some good ideas and your implementation seems clean.

Unfortunately it seems that some autoformater somewhere went rogue so there's a lot more changes than necessary or relevant to the issue being worked on. 

Do you think you could undo the irrelevant changes to the *.py files? Then happy to approve your PR

2024-01-06 19:28 UTC, northdpole commented on application/cmd/cre_main.py
> +                else (
is this a necessary change?

2024-01-06 19:28 UTC, northdpole commented on application/database/db.py
> -                    "Related": node.related,
same here, it seems like this is changing style without changing the functionality

2024-01-06 19:28 UTC, northdpole commented on application/database/db.py
> -            else [],
same with this change, could it be the case of linter gone wild?

2024-01-06 19:28 UTC, northdpole commented on application/database/db.py
> -            else [],
same with this one

2024-01-06 19:28 UTC, northdpole commented on application/database/db.py
> -            if parse_links
same with this one

2024-01-06 19:28 UTC, northdpole commented on application/database/db.py
> +                    "tags": (
same here

2024-01-06 19:28 UTC, northdpole commented on application/frontend/src/components/DocumentNode/DocumentNode.tsx
> -import { Icon } from 'semantic-ui-react';
thanks for removing unused imports :-) 
if you know how we can do this automatically or add this to linting it'd be great!

2024-01-06 19:28 UTC, northdpole commented on application/frontend/src/components/DocumentNode/DocumentNode.tsx
> -  const SimpleView = () => {
good idea moving this out into its own component

2024-01-06 19:28 UTC, northdpole commented on application/frontend/src/components/DocumentNode/DocumentNode.tsx
> +                        <div key={`document-node-container-${type}-${idx}-${i}`}>
good idea making the key unique but referenceable

2024-01-06 19:28 UTC, northdpole commented on application/frontend/src/pages/Search/components/BodyText.tsx
> +          <a href="/cre/764-507"> CRE 764-507 </a> or <a href="/cre/581-525">CRE 581-525</a> to see the{' '}
just wondering: how's the {' '} different than the whitespace that was there before

2024-01-06 19:28 UTC, northdpole commented on application/tests/cre_main_test.py
> -                "Standard NIST 800-53 v5-hyperlink": "https://example.com/nist-800-53-v5",
is this change necessary?
it's just adding parentheses


same for all changes in this file

2024-01-06 19:28 UTC, northdpole commented on application/tests/defs_test.py
> -                                    "section": "SESSION-MGT-TOKEN-DIRECTIVES-DISCRETE-HANDLING",
is the parentheses addition necessary here?

2024-01-06 19:28 UTC, northdpole commented on application/tests/spreadsheet_parsers_test.py
> -                "Standard NIST 800-53 v5-hyperlink": "https://example.com/nist-800-53-v5",
are the changes in this file necessary?

2024-01-06 19:28 UTC, northdpole commented on application/tests/web_main_test.py
> +            "cd": (
are the changes in this file necessary or relevant to the issue being worked on?

2024-01-06 19:40 UTC, northdpole commented
> > Hey @restylianos , thanks a lot for the PR! Can you please fix the linting?
> 
> Hi, @northdpole it should be ok now. Please keep in mind that there is an inconsistency between the development environment and the lint code base workflow **[local setup]** `black --version black, 24.1a1 Python (CPython) 3.10.12` **[super-linter@v4]** `black==22.12.0`

huh, good catch!
Guess the super linter is a couple major versions behind, still it seems to be backwards compatible so this does not seem to be a problem for now

2024-01-06 20:08 UTC, restylianos commented
@northdpole Sure I will drop the python changes asap and I will also investigate the suggested improvements related to eslint.

2024-01-07 16:56 UTC, restylianos commented
@northdpole Hi, I just dropped the python changes. 

#### Workflow fail and unnecessary python file changes
The python changes were created after running make lint locally. The first workflow fail (4 files), was related to the inconstancy between my environment and super-linter@v4 which lead to a different result. Downgrading black to version 22.12.0 solved this issue and running make lint does no longer format additional python files. 

#### Eslint
> thanks for removing unused imports :-). if you know how we can do this automatically or add this to linting it'd be great! 

This could be achieved by introducing eslint to the lint process . The yarn run lint command **currently leads to the execution of prettier** ` "lint": "prettier --write '**/*.tsx' '**/*.ts' '**/*.js'",` . Including eslint to the lint process introduced too many changes related to 23 {\*.ts,\*.tsx} files  and dev dependencies. The following output was produced after a POC version `✖ 194 problems (111 errors, 83 warnings)`. I would be happy to work on the required changes, however, I think that this should be a different issue in order to avoid mixing issues up, in a single pr.

2024-04-06 18:12 UTC, closed without merging